[tool.isort]
profile = "black"
skip_glob = ["drakrun/data/**/*", "drakrun/tools/**/*", "drakrun/web/frontend/**/*"]

[tool.black]
exclude = "drakrun/(data|tools|web/frontend)"

[tool.lint-python]
lint-version = "2"
source = "./drakrun"
use-mypy = false
