#!/bin/bash

set -e

case "$1" in
    configure)
        # continue with the script
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
    ;;
esac

mkdir -p /var/lib/drakcore/minio

/opt/venvs/drakcore/bin/drak-config-setup

systemctl daemon-reload
systemctl enable --now drak-system.service
systemctl enable --now drak-web.service
systemctl enable --now drak-minio.service
