#!/bin/bash

set -e

case "$1" in
    remove|purge)
        # TODO continue with the script
    ;;

    deconfigure|disappear|upgrade|failed-upgrade|abort-install|abort-install|abort-upgrade)
    ;;

    *)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
    ;;
esac

systemctl disable --now drak-minio.service
systemctl disable --now drak-system.service
systemctl disable --now drak-web.service

