#!/bin/bash

set -e

case "$1" in
    remove)
    ;;
    
    purge)
        rm -rf /var/lib/drakrun
    ;;

    deconfigure|disappear|upgrade|failed-upgrade|abort-install|abort-install|abort-upgrade)
    ;;

    *)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
    ;;
esac
