import uuid
from typing import Annotated, List, Optional

from flask_openapi3 import FileStorage
from pydantic import AfterValidator, BaseModel, Field, RootModel


class APIErrorResponse(BaseModel):
    error: str = Field(description="Error message")


class UploadFileForm(BaseModel):
    file: FileStorage
    timeout: Optional[int] = Field(default=None, description="Analysis timeout")
    file_name: Optional[str] = Field(default=None, description="Target file name")
    file_path: Optional[str] = Field(default=None, description="Target file path")
    start_command: Optional[str] = Field(default=None, description="Start command")
    plugins: Optional[List[str]] = Field(
        default=None, description="Plugins to use (in JSON array string)"
    )
    preset: Optional[str] = Field(default=None, description="Analysis settings preset")
    no_internet: Optional[bool] = Field(
        default=False, description="Disable Internet connection"
    )
    no_screenshots: Optional[bool] = Field(
        default=False, description="Disable screenshots"
    )
    extract_archive: Optional[bool] = Field(
        default=False, description="Sample is an archive, extract it"
    )
    archive_entry_path: Optional[str] = Field(
        default=None, description="Path inside archive to execute (for archive mode)"
    )
    archive_password: Optional[str] = Field(
        default=None, description="Archive password"
    )


class UploadAnalysisResponse(BaseModel):
    task_uid: str = Field(description="Unique analysis ID")


class AnalysisResponse(BaseModel):
    id: str = Field(description="Unique analysis ID")
    status: str = Field(description="Analysis status")
    time_started: Optional[str] = Field(
        default=None, description="Analysis start time in ISO format"
    )
    time_ended: Optional[str] = Field(
        default=None, description="Analysis end time in ISO format"
    )


AnalysisListResponse = RootModel[List[AnalysisResponse]]


class AnalysisRequestPath(BaseModel):
    task_uid: Annotated[str, AfterValidator(lambda x: str(uuid.UUID(x, version=4)))] = (
        Field(description="Unique analysis ID")
    )


class AnalysisFileRequestQuery(BaseModel):
    filename: str


class LogsRequestPath(AnalysisRequestPath):
    log_type: str


class ProcessInfoRequestPath(AnalysisRequestPath):
    seqid: int


class ProcessLogsRequestPath(AnalysisRequestPath):
    log_type: str
    seqid: int


class ScreenshotRequestPath(AnalysisRequestPath):
    which: int


class KartonResultsUploadForm(BaseModel):
    # token generated by karton integration postprocessing plugin
    token: str = Field(description="The upload token for this analysis")
    data: FileStorage = Field(description="Data to upload to report")
    key: str = Field(default=None, description="Key name for data in report")


class KartonResultsUploadPath(BaseModel):
    analysis_id: Annotated[
        str, AfterValidator(lambda x: str(uuid.UUID(x, version=4)))
    ] = Field(description="Unique analysis ID")


class KartonResultsUploadResponse(BaseModel):
    status: str = Field(description="Upload status")
    key: str = Field(description="Uploaded Redis hash key")
